name: super_a_p_p
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"   # â† NECESARIO para los paquetes de FlutterFlow

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  auto_size_text: 3.0.0
  cached_network_image: 3.4.1
  cached_network_image_platform_interface: 4.1.1
  cached_network_image_web: 1.3.1
  card_swiper: ^3.0.1
  collection: 1.19.1
  equatable: 2.0.7
  ff_commons:
    path: ./dependencies/ff_commons
  ff_theme:
    path: ./dependencies/ff_theme
  flutter_animate: 4.5.0
  flutter_cache_manager: 3.4.1
  font_awesome_flutter: 10.7.0
  from_css_color: 2.0.0
  go_router: 12.1.3
  google_fonts: 6.1.0
  http: 1.4.0
  intl: 0.20.2
  json_path: 0.7.2
  mime_type: 1.0.0
  page_transition: 2.1.0

  
  panic_a_p_p_93xbys:
    path: ./dependencies/panic_a_p_p_93xbys

  path_provider: 2.1.4
  provider: 6.1.5
  shared_preferences: 2.5.3
  shimmer: ^3.0.0
  sqflite: 2.3.3+1
  timeago: 3.7.1

  url_launcher: ^6.3.1
  cupertino_icons: ^1.0.0

dependency_overrides:
  http: 1.4.0
  uuid: ^4.0.0

dev_dependencies:
  flutter_lints: 4.0.0
  lints: 4.0.0
  flutter_test:
    sdk: flutter


  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/jsons/
